### ISSUE TITLE
Disabling transcoder in TCP version does not work.

### ISSUE THREAD

**Issue by vk3jed** [n7tae/urfd#10]
I've just installed the TCP branch of urfd.  I currently don't have a transcoder configured, so I attempted to disable transcoding in urfd.  I followed the instructions and set  Port = 0 in the transcoder section of urfd.ini.  However, this does not work, and urfd still listens on TCP port 10100.  

> Jun  3 17:24:49 44-gateway urfd[3045210]: IPv4 binding address is '0.0.0.0'
Jun  3 17:24:49 44-gateway urfd[3045210]: Starting URF432 3.1.2-dht
Jun  3 17:24:50 44-gateway urfd[3045210]: Waiting at [::]:10100 for transcoder connection for module A...

If I set the TCP port to any other value, urfd listens on the specified port as expected for the transcoder.

Because urfd won't start until the transcoder is active, this prevents any useful operation.

**Comment by n7tae** [comment]
inicheck would have found this error. Shame on me for not checking this before I published the tcp branch. This is fixed now.
