### ISSUE TITLE
Error receiving M17 audio packets from W0CHP hotspot and DroidStar

### ISSUE THREAD

**Issue by jessebrownfl** [n7tae/urfd#2]
M17 clients connect without any errors but when audio transmit is attempted the logs are filled with the following...

```
Sep  7 16:52:53 vsrv44 urfd[124548]: Unknown M17 packet from [redacted]:
Sep  7 16:52:53 vsrv44 urfd[124548]: 0000:  4D 31 37 20 E1 48 1D EB C3 31 3A ED 00 00 84 2C    *M17 .H...1:....,*
Sep  7 16:52:53 vsrv44 urfd[124548]: 0010:  B2 BB 00 05 00 00 00 00 00 00 00 00 00 00 00 00    *................*
Sep  7 16:52:53 vsrv44 urfd[124548]: 0020:  00 00 80 00 01 00 09 43 9C E4 21 08 01 00 09 43    *.......C..!....C*
Sep  7 16:52:53 vsrv44 urfd[124548]: 0030:  9C E4 21 08 00 00                                  *..!...*
```

The same devices are able to connect with the M17-M17 reflector and have 2-way audio.

I built urfd from this project's source on an Ubuntu 22.04 LTS system. It was built from commit 70cc0107eeb75bf3dee73bba4b97489e7fd572d1

Please let me know if I can provide more information.

**Comment by mfiscus** [comment]
I am experiencing the exact same issue.

`
Unknown M17 packet from 10.0.0.10:
0000:  4D 31 37 20 00 01 06 17 10 79 AA ED 29 B9 27 12    *M17 .....y..).'.*
0010:  AC 3F 00 05 00 00 00 00 00 00 00 00 00 00 00 00    *.?..............*
0020:  00 00 00 10 99 C3 4A 73 5A F5 AF 28 42 43 85 5B    *......JsZ..(BC.[*
0030:  1E F7 21 C8 28 FC                                  *..!.(.*
`

I'm also using Ubuntu 22.04 LTS (in a [docker container](https://github.com/mfiscus/urfd-docker)). It was built from commit [70cc010](https://github.com/n7tae/urfd/commit/70cc0107eeb75bf3dee73bba4b97489e7fd572d1)

**Comment by n7tae** [comment]
In both cases, the encoded destination callsigns (starting at the 7th byte) decode to M17 reflectors. The first example decodes to M17-164 E and the second example decodes to M17-847 A.

These were rejected because they are illegal callsigns in the domain where urfd operates.
