### ISSUE TITLE
Dashboard is blank when using a non-numeric ServiceName

### ISSUE THREAD

**Issue by coolacid** [n7tae/urfd#5]
In the reflector class, when loading the XML file there is a check to see if the ID is numeric: 

https://github.com/n7tae/urfd/blob/main/dashboard/pgs/class.reflector.php#L46-L49

```
         if (!is_numeric($this->ServiceName)) {
            $this->ServiceName = null;
            return false;
         }
```

This has the effect that when the dashboard is used with `urfd` using a non-numeric name ie; `URFZZZ` the dashboard remains blank. 

Just wondering what the reason for this was as it impacts the reflector ID I choose.

**Comment by n7tae** [comment]
Sorry for the long  delay. This if clause was inherited from the xlxd repo (dashboard2). They have a more flexible if clause in their other dashboard. I've put this in my repo and will merge it soon into main. I'll close this, but if you see an issue, please reopen it. I'll try not to take so long in responding!

**Comment by coolacid** [comment]
No problem @n7tae Thanks for the clarification!
