### ISSUE TITLE
Issue with rconfig script

### ISSUE THREAD

**Issue by W2GLD** [n7tae/urfd#8]
Unable to edit the call sign "cs" value when running this script, I can freely edit all other values.  Not sure if this is why I cannot compile one not; however, I cannot get past this set.

**Comment by n7tae** [comment]
URF callsign must begin with "URF". Could that be your problem?

**Comment by W2GLD** [comment]
The value 'CALLSIGN" is confusing from the normal.  It looks as that field is limited to 6-characters, but one assumes "CALLSIGN" means your "CALLSIGN" and not a URF###.

**Comment by n7tae** [comment]
Sorry if it wasn't obvious to you. REF reflector callsigns are always REF###. XRF reflector callsign are always XRF###. XLX reflector callsigns are always XLX###.

At the next release cycle, there will be an additional sentence in the README.md file.
